name: appwrite
version: 15.0.0
description: Appwrite is an open-source self-hosted backend server that abstract and simplify complex and repetitive development tasks behind a very simple REST API
homepage: https://appwrite.io
repository: https://github.com/appwrite/sdk-for-flutter
issue_tracker: https://github.com/appwrite/sdk-generator/issues
documentation: https://appwrite.io/support
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cookie_jar: ^4.0.8
  device_info_plus: ^11.3.3
  flutter_web_auth_2: ^4.1.0
  http: '>=0.13.6 <2.0.0'
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  web_socket_channel: ^3.0.2
  web: ^1.1.1

dev_dependencies:
  path_provider_platform_interface: ^2.1.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
