name: appwrite
version: 5.0.0
description: Appwrite is an open-source self-hosted backend server that abstract and simplify complex and repetitive development tasks behind a very simple REST API
homepage: https://appwrite.io
repository: https://github.com/appwrite/sdk-for-flutter
issue_tracker: https://github.com/appwrite/sdk-generator/issues
documentation: https://appwrite.io/support
environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cookie_jar: ^3.0.1
  device_info_plus: ^3.2.2
  
  http: ^0.13.4
  package_info_plus: 1.4.2
  path_provider: ^2.0.9
  web_socket_channel: ^2.2.0
  # flutter_web_auth: ^0.4.1
  # Temporary fork of flutter_web_auth addressing issue:
  # https://github.com/flutter/flutter/issues/103561#issuecomment-1126416045
  flutter_web_auth:
    git:
      url: https://github.com/noga-dev/flutter_web_auth.git

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
